spring:
    application:
        name: mini_jira

    datasource:
        url: ${AIVEN_URL}
        username: ${AIVEN_USERNAME}
        password: ${AIVEN_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update

        show-sql: true
        open-in-view: true

    threads:
        virtual:
            enabled: true
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            password: ${REDIS_PASSWORD}
            ssl: 
                enabled: true

    rabbitmq:
        addresses: ${RABBITMQ_URL}

sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: ${SENDGRID_FROM_EMAIL}


management:
    endpoints:
        web:
            exposure:
                include: health, metrics, info
    endpoint:
        health:
            show-details: always

logging:
    level:
        root: INFO
        '[com.example.mini_jira]': DEBUG
        '[org.hibernate.sql]': DEBUG
    file: 
        name: mini-jira-logs.log
